// This file is automatically generated. Do not edit it directly.
import { createClient } from '@supabase/supabase-js';
import type { Database } from './types';

const SUPABASE_URL = "https://nuzdziydglvswknxvrbh.supabase.co";
const SUPABASE_PUBLISHABLE_KEY = "eyJhbGciOiJIUzI1NiIsInR5cCI6IkpXVCJ9.eyJpc3MiOiJzdXBhYmFzZSIsInJlZiI6Im51emR6aXlkZ2x2c3drbnh2cmJoIiwicm9sZSI6ImFub24iLCJpYXQiOjE3MzgwMDk0NDYsImV4cCI6MjA1MzU4NTQ0Nn0.8QeI0xzc0j5J5wXS28OLNOUzjeVCwqk5xvSVBzmjJdg";

// Import the supabase client like this:
// import { supabase } from "@/integrations/supabase/client";

export const supabase = createClient<Database>(SUPABASE_URL, SUPABASE_PUBLISHABLE_KEY);